apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-ai-router
  labels:
    app: staging-ai-router
    environment: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: staging-ai-router
  template:
    metadata:
      labels:
        app: staging-ai-router
        environment: staging
    spec:
      containers:
      - name: ai-router
        image: gcr.io/the-feedfactory/ai-router:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: TARGET_URL
          value: "http://10.100.0.1"
        - name: NODE_ENV
          value: "staging"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5