apiVersion: v1
kind: Service
metadata:
  name: ai-router
  labels:
    app: ai-router
spec:
  type: ClusterIP
  selector:
    app: ai-router
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http